# See https://pre-commit.com/ for usage and config

repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.3
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3.8 # Should be a command that runs python3.6+

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3 # pick a git hash / tag to point to
    hooks:
      - id: flake8
