# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import services_pb2 as services__pb2


class InformationStub(object):
  """The Information service definition.

  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  // Sends a file
  rpc Chunker(google.protobuf.Empty) returns (stream Chunk) {}
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendCounter = channel.unary_unary(
        '/services.Information/SendCounter',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.CounterReply.FromString,
        )
    self.SendBooks = channel.unary_unary(
        '/services.Information/SendBooks',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.BooksReply.FromString,
        )
    self.SendDB = channel.unary_stream(
        '/services.Information/SendDB',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.File.FromString,
        )
    self.SendHour = channel.unary_unary(
        '/services.Information/SendHour',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.HourReply.FromString,
        )
    self.SendBook = channel.unary_unary(
        '/services.Information/SendBook',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.BookReply.FromString,
        )


class InformationServicer(object):
  """The Information service definition.

  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  // Sends a file
  rpc Chunker(google.protobuf.Empty) returns (stream Chunk) {}
  """

  def SendCounter(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendBooks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendDB(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendHour(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InformationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendCounter': grpc.unary_unary_rpc_method_handler(
          servicer.SendCounter,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.CounterReply.SerializeToString,
      ),
      'SendBooks': grpc.unary_unary_rpc_method_handler(
          servicer.SendBooks,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.BooksReply.SerializeToString,
      ),
      'SendDB': grpc.unary_stream_rpc_method_handler(
          servicer.SendDB,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.File.SerializeToString,
      ),
      'SendHour': grpc.unary_unary_rpc_method_handler(
          servicer.SendHour,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.HourReply.SerializeToString,
      ),
      'SendBook': grpc.unary_unary_rpc_method_handler(
          servicer.SendBook,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.BookReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'services.Information', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
